apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-conf-logs
  namespace: logging
  annotations:
    note: 用來掛載到容器裡的預設資料夾`/etc/telegraf/`
data:
  telegraf.conf: |
    [[inputs.tail]]
        ## File names or a pattern to tail.
        ## These accept standard unix glob matching rules, but with the addition of
        ## ** as a "super asterisk". ie:
        ##   "/var/log/**.log"  -> recursively find all .log files in /var/log
        ##   "/var/log/*/*.log" -> find all .log files with a parent dir in /var/log
        ##   "/var/log/apache.log" -> just tail the apache log file
        ##
        ## See https://github.com/gobwas/glob for more examples
        ##
        files = [
            "var/log/containers/**.log",
            "var/log/pods/**.log",
        ]

        name_override = "syslog" # 要儲存成的measurement

        ## Read file from beginning.
        # from_beginning = true

        ## Whether file is a named pipe
        # pipe = false

        ## Method used to watch for file updates.  Can be either "inotify" or "poll".
        watch_method = "inotify"

        ## Data format to consume.
        ## Each data format has its own unique set of configuration options, read
        ## more about them here:
        ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
        # 可使用關鍵字
        # https://github.com/elastic/logstash/blob/v1.4.0/patterns/grok-patterns
        data_format = "grok"
        grok_patterns = ['%{TIMESTAMP_ISO8601:timestamp:ts-"2006-01-02T15:04:05.9999999Z07:00"} %{WORD:std} %{WORD:from} %{ALL:msg}']
        grok_custom_patterns = '''
        ALL ([\w\d\s\W\D\S]{0,}$)
        '''

    [[outputs.influxdb]]
      urls = ["http://influxdb.monitoring.svc.cluster.local:8086"]
      timeout = "5s"
      content_encoding = "gzip"
      database = "telegraf"
      # retention_policy = "autogen"
