kind: pipeline
type: kubernetes
name: default

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    volumes:
      - name: project
        path: /root/gola
    environment:
      CLONE_DIR: /root/gola
    commands:
      - cd $CLONE_DIR
      - if ls .git 1>/dev/null 2>&1 ; then echo project has clone; else git clone $DRONE_GIT_HTTP_URL .; fi
      - git fetch origin $DRONE_COMMIT
      - git reset --hard $DRONE_COMMIT
      - cd /drone/src
      - cp -R $CLONE_DIR/* .

  - name: build
    image: golang:1.14.10
    volumes:
      - name: gocache
        path: /root/.cache/go-build
    commands:
      - go build -mod vendor -v -ldflags "-X 'gola/global.AppVersion=v1' -X 'gola/global.BuildTime=$(date -u '+%Y-%m-%dT%I:%M:%SZ')' -X 'gola/global.GoVersion=$(go version)'" -o gola_v1
      - go build -mod vendor -v -ldflags "-X 'gola/global.AppVersion=v2' -X 'gola/global.BuildTime=$(date -u '+%Y-%m-%dT%I:%M:%SZ')' -X 'gola/global.GoVersion=$(go version)'" -o gola_v2

  - name: publish
    image: docker:dind
    volumes:
      - name: docker_run
        path: /var/run
      - name: docker_lib
        path: /var/lib
    commands:
      - docker version
      - docker build -t registry:5000/gola/web:v1_${DRONE_COMMIT} -t registry:5000/gola/web:v1 -f ./docker/drone.Dockerfile --build-arg version=_v1 .
      - docker build -t registry:5000/gola/web:v2_${DRONE_COMMIT} -t registry:5000/gola/web:v2 -f ./docker/drone.Dockerfile --build-arg version=_v2 .
      - docker push registry:5000/gola/web:v1_${DRONE_COMMIT}
      - docker push registry:5000/gola/web:v1
      - docker push registry:5000/gola/web:v2_${DRONE_COMMIT}
      - docker push registry:5000/gola/web:v2
      - docker system prune -f
      - docker volume prune -f

  - name: deploy_v1
    image: quay.io/honestbee/drone-kubernetes
    settings:
      namespace: default
      deployment:
        - gola-server
        - gorpc-greet-v1
        - grpc-greet-v1
        - http-greet-v1
      container: server
      repo: registry:5000/gola/web
      tag: v1_${DRONE_COMMIT}

  - name: deploy_v2
    image: quay.io/honestbee/drone-kubernetes
    settings:
      namespace: default
      deployment:
        - gorpc-greet-v2
        - grpc-greet-v2
        - http-greet-v2
      container: server
      repo: registry:5000/gola/web
      tag: v2_${DRONE_COMMIT}

services:
  - name: dind
    image: docker:dind
    privileged: true
    command:
      - /usr/local/bin/dockerd
      - --data-root=/root/.cache/docker-build
      - --host=unix:///var/run/docker.sock
      - --insecure-registry=registry:5000
    volumes:
      - name: docker_run
        path: /var/run
        temp: {}
      - name: docker_cache
        path: /root/.cache/docker-build
        host:
          path: /root/.cache/docker-build

volumes:
  - name: project
    host:
      path: /root/gola
  - name: gocache
    host:
      path: /root/.cache/go-build
  - name: docker_cache
    host:
      path: /root/.cache/docker-build
  - name: docker_run
    temp: {}
