version: '3'

services:

    # 編譯檔案
    build:
        image: golang:1.11
        command: go build -o gola
        working_dir: /go/src/gola
        volumes:
            - .:/go/src/gola
            - gopath:/go
        environment:
            - GO111MODULE=on

    # 開發容器
    web-dev:
        image: golang:1.11
        command: ./gola server
        working_dir: /app
        restart: on-failure
        ports:
            - "${PORT}:8000"
        environment:
            - GIN_MODE=debug
            - APP_ENV=docker
            - PORT=8000
        volumes:
            - .:/app
        depends_on:
            - build
            - db

    # 編譯映像檔案
    build-image:
        build: .
        image: 127.0.0.1:5000/gola/web_${APP_ENV}

    # 網站服務
    web:
        build: .
        image: 127.0.0.1:5000/gola/web_${APP_ENV}
        command: server
        restart: always
        ports:
            - "${PORT}:8000"
        environment:
            - GIN_MODE=debug
            - APP_ENV=${APP_ENV}
            - PORT=8000
        volumes:
            - storage_app:/app/storage/app
            - storage_logs:/app/storage/logs

    # 排程服務
    cronjob:
        build: .
        image: 127.0.0.1:5000/gola/web_${APP_ENV}
        command: schedule
        restart: always
        environment:
            - APP_ENV=${APP_ENV}
        volumes:
            - storage_app:/app/storage/app
            - storage_logs:/app/storage/logs

    adminer:
        image: adminer
        ports:
            - "8080:8080"

    db:
        image: mysql:5.6
        ports:
            - "3306:3306"
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: qwe123
            MYSQL_DATABASE: gola
        volumes:
            - data:/var/lib/mysql
        depends_on:
            - adminer

volumes:
    data:
        driver: local
    gopath:
        driver: local
    storage_app:
        driver: local
    storage_logs:
        driver: local
