version: '3'

services:

    # 網站服務
    web:
        build:
            context: .
            args:
                - ENTER=server
                - TG_TOKEN=${TG_TOKEN}
                - TG_CHAT_ID=${TG_CHAT_ID}
        image: registry.heroku.com/golar/web:latest
        command: server
        restart: always
        ports:
            - "${PORT}:8000"
        environment:
            - GIN_MODE=debug
            - APP_ENV=${APP_ENV}
            - APP_SITE=${APP_SITE}
            - PORT=8000
        volumes:
            - storage_app:/app/storage/app
            - storage_logs:/app/storage/logs

    # 排程服務
    cronjob:
        build: .
        image: 127.0.0.1:5000/gola/web_${APP_ENV}
        command: schedule
        restart: always
        environment:
            - APP_ENV=${APP_ENV}
        volumes:
            - storage_app:/app/storage/app
            - storage_logs:/app/storage/logs

    adminer:
        image: adminer
        ports:
            - "8080:8080"

    db:
        image: mysql:5.6
        ports:
            - "3306:3306"
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: qwe123
            MYSQL_DATABASE: gola
        volumes:
            - data:/var/lib/mysql
        depends_on:
            - adminer

volumes:
    data:
        driver: local
    gopath:
        driver: local
    storage_app:
        driver: local
    storage_logs:
        driver: local
