version: "3"

services:
    # 網站服務
    web:
        build:
            context: .
            args:
                - ENTER=server
                - BOT_TOKEN=${BOT_TOKEN}
                - BOT_CHAT_ID=${BOT_CHAT_ID}
        image: localhost:5000/gola/web:latest
        command: server
        restart: always
        ports:
            - "${PORT}:8000"
        environment:
            - GIN_MODE=debug
            - APP_ENV=${APP_ENV}
            - APP_SITE=${APP_SITE}
            - PORT=8000
        volumes:
            - ./storage:/app/storage

    # 排程服務
    cronjob:
        build:
            context: .
            args:
                - ENTER=schedule
                - BOT_TOKEN=${BOT_TOKEN}
                - BOT_CHAT_ID=${BOT_CHAT_ID}
        image: localhost:5000/gola/web:latest
        command: schedule
        restart: always
        environment:
            - APP_ENV=${APP_ENV}
        volumes:
            - ./storage:/app/storage

    db:
        image: mysql:5.6
        ports:
            - "3306:3306"
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: qwe123
            MYSQL_DATABASE: gola
        volumes:
            - db:/var/lib/mysql
        depends_on:
            - adminer

    cache:
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - cache:/data
        depends_on:
            - redis-admin

    adminer:
        image: adminer
        ports:
            - "8080:8080"

    redis-admin:
        image: rediscommander/redis-commander
        ports:
            - "8081:8081"
        environment:
            - REDIS_HOSTS=redis:cache:6379:0

volumes:
    db:
        driver: "local"
    cache:
        driver: "local"
