apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
      version: latest
  template:
    metadata:
      labels:
        app: grafana
        version: latest
      annotations:
        note1: chronograf no need password
        note2: grafana's username/password = admin/admin
    spec:
      containers:
        - name: chronograf
          image: chronograf:1.8
          args: ["--influxdb-url=http://influxdb:8086"]
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
        - name: grafana
          image: grafana/grafana:7.3.1
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
  namespace: monitoring
spec:
  ports:
    - name: http-chronograf
      port: 8888
    - name: http-grafana
      port: 3000
  selector:
    app: grafana
