apiVersion: v1
kind: ServiceAccount
metadata:
  name: telegraf-kubernetes
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: telegraf-kubernetes
  annotations:
    note: "權限參照: https://www.lagou.com/lgeduarticle/111606.html"
rules:
  - apiGroups: [""]
    resources:
      - nodes/proxy
      - nodes
      - namespaces
      - endpoints
      - pods
      - services
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - nodes/metrics
    verbs: ["get"]
  - nonResourceURLs:
      - /metrics
    verbs: ["get"]
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: telegraf-kubernetes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: telegraf-kubernetes
subjects:
  - kind: ServiceAccount
    name: telegraf-kubernetes
    namespace: monitoring
