apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: telegraf-kubernetes
  namespace: monitoring
  labels:
    app: telegraf-kubernetes
    run: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf-kubernetes
      run: telegraf
  template:
    metadata:
      labels:
        app: telegraf-kubernetes
        run: telegraf
    spec:
      serviceAccount: telegraf-kubernetes
      containers:
        - name: telegraf
          image: telegraf:1.16
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - name: telegraf-conf
              mountPath: /etc/telegraf
      volumes:
        - name: telegraf-conf
          configMap:
            name: telegraf-conf-kubernetes
