[app]
    name = "gola"       # 專案名稱
    env = "prod"        # 專案環境
    site = "default"    # 專案站別
    debug = false       # 開啟Debug模式
    salt = "this is your pernal salt"   # 專案雜湊碼

[server]
    ip = "web"          # 伺服器的IP
    host = "localhost"  # 伺服器的Host
    port = "8000"       # 伺服器的Port
    auto_port = true    # 啟用自動尋找環境變數:PORT
    secure = false      # 是否要安全憑證
    max_conn = 100000   # 最大連線數量

[log]
    mode = "std"        # Log紀錄模式： std, file, std+file
    prefix = "GOLA"     # Log前綴

[database]
    [database.default_master]
        db = "gola"
        host = "db"
        port = "3306"
        username = "root"
        password = "qwe123"
        max_conn = 10

    [database.default_slave]
        db = "gola"
        host = "db"
        port = "3306"
        username = "root"
        password = "qwe123"
        max_conn = 10

[cache]
    [cache.default_master]
        host = "cache"
        port = "6379"
        password = ""
        max_conn = 100

    [cache.default_slave]
        host = "cache"
        port = "6379"
        password = ""
        max_conn = 100

[service]
    [service.google]
        ip = "google.com"
        host = "google.com"
        port = ""
        secure = true
        api_key = ""
