apiVersion: apps/v1
kind: Deployment
metadata:
  name: gola-schedule
  labels:
    repo: gola
    app: schedule
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      repo: gola
      app: schedule
  template:
    metadata:
      labels:
        repo: gola
        app: schedule
    spec:
      containers:
        - name: gola-schedule
          image: localhost:5000/gola/web:latest
          command:
            - ./gola
          args:
            - schedule
          env:
            - name: APP_SITE
              value: schedule
          envFrom:
            - configMapRef:
                name: env-prod
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
