# /**
#  * ============================
#  * 背景清單
#  * ============================
#  * 請依照背景資訊登記在下面的清單
#  *
#  * 背景資訊格式
#  * name - 背景名稱
#  * spec - 執行時間週期
#  * cmd  - 執行指令，請參照 app/console/kernal.go
#  * overlapping - 是否可重複執行
#  * note - 背景說明
#  *
#  */

[[job]]
name = "demo"
spec = "*/1 * * * * *"
cmd = "demo"
overlapping = false
note = "只是Demo"
