apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: phpmyadmin
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      run: phpmyadmin
  template:
    metadata:
      labels:
        run: phpmyadmin
    spec:
      restartPolicy: Always
      containers:
        - image: phpmyadmin/phpmyadmin:4.8
          imagePullPolicy: IfNotPresent
          name: phpmyadmin
          env:
            - name: PMA_HOSTS
              value: "mysql"
            - name: PMA_PORT
              value: "3306"
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
