[app]
env = "qatest"
ip = "127.0.0.1"
host = "localhost:8001"
port = ":8001"
secure = false
debug = true

[database_master]
db = "gola_qatest"
host = "10.0.2.15"
port = "3306"
username = "root"
password = "qwe123"

[database_slave]
db = "gola_qatest"
host = "10.0.2.15"
port = "3306"
username = "root"
password = "qwe123"

[server]
    [server.google]
        ip = "google.com"
        port = ":80"
        host = "google.com"
        secure = false
        api_key = ""
