definitions:
  bootstrap.AppConf:
    properties:
      debug:
        description: 開啟Debug模式
        type: boolean
      env:
        description: 專案環境
        type: string
      name:
        description: 專案名稱
        type: string
      salt:
        description: 專案雜湊碼
        type: string
      site:
        description: 專案站別
        type: string
    type: object
  bootstrap.BotConf:
    properties:
      chatID:
        type: integer
      debug:
        type: boolean
      token:
        type: string
    type: object
  bootstrap.CacheConf:
    properties:
      db:
        type: integer
      host:
        type: string
      maxConn:
        type: integer
      password:
        type: string
      port:
        type: integer
    type: object
  bootstrap.CacheList:
    properties:
      defaultMaster:
        $ref: '#/definitions/bootstrap.CacheConf'
      defaultSlave:
        $ref: '#/definitions/bootstrap.CacheConf'
    type: object
  bootstrap.Config:
    properties:
      app:
        $ref: '#/definitions/bootstrap.AppConf'
      bot:
        $ref: '#/definitions/bootstrap.BotConf'
      caches:
        $ref: '#/definitions/bootstrap.CacheList'
      databases:
        $ref: '#/definitions/bootstrap.DatabaseList'
      log:
        $ref: '#/definitions/bootstrap.LogConf'
      server:
        $ref: '#/definitions/bootstrap.ServerConf'
      services:
        $ref: '#/definitions/bootstrap.ServiceList'
    type: object
  bootstrap.DatabaseConf:
    properties:
      db:
        type: string
      host:
        type: string
      maxConn:
        type: integer
      password:
        type: string
      port:
        type: integer
      username:
        type: string
    type: object
  bootstrap.DatabaseList:
    properties:
      defaultMaster:
        $ref: '#/definitions/bootstrap.DatabaseConf'
      defaultSlave:
        $ref: '#/definitions/bootstrap.DatabaseConf'
    type: object
  bootstrap.LogConf:
    properties:
      mode:
        description: Log紀錄模式： std, file, std+file
        type: string
      prefix:
        description: Log前綴
        type: string
    type: object
  bootstrap.ServerConf:
    properties:
      host:
        description: 伺服器的Host
        type: string
      ip:
        description: 伺服器的IP
        type: string
      maxConn:
        description: 最大連線數量
        type: integer
      port:
        description: 伺服器的Port
        type: integer
      secure:
        description: 是否要安全憑證
        type: boolean
    type: object
  bootstrap.ServiceConf:
    properties:
      apikey:
        type: string
      host:
        type: string
      ip:
        type: string
      port:
        type: integer
      secure:
        type: boolean
    type: object
  bootstrap.ServiceList:
    properties:
      google:
        $ref: '#/definitions/bootstrap.ServiceConf'
    type: object
  errorcode.APIError:
    properties:
      error_code:
        type: integer
      error_text:
        type: string
    type: object
  response.API:
    properties:
      error_code:
        type: integer
      error_text:
        type: string
      result:
        type: object
    type: object
  swagger.ConfigRequest:
    properties:
      level:
        description: 使用者階層。 0:會員, 1:管理者, 2:系統管理者
        example: 0
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/config:
    post:
      consumes:
      - application/json
      description: 範例
      parameters:
      - description: 使用者等級
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/swagger.ConfigRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 回傳設定資料
          schema:
            $ref: '#/definitions/bootstrap.Config'
        "403":
          description: 回傳權限不足
          schema:
            $ref: '#/definitions/response.API'
      summary: 範例
      tags:
      - 範例
  /api/gorpc/hello:
    get:
      description: 範例
      responses:
        "200":
          description: hello world
          schema:
            type: string
      summary: gorpc greet
      tags:
      - 範例
  /api/grpc/hello:
    get:
      description: 範例
      responses:
        "200":
          description: hello world
          schema:
            type: string
      summary: grpc greet
      tags:
      - 範例
  /api/http/hello:
    get:
      description: 範例
      responses:
        "200":
          description: hello world
          schema:
            type: string
      summary: http greet
      tags:
      - 範例
  /api/seed:
    post:
      description: 在DB產生資料
      responses:
        "200":
          description: 回傳執行狀態
          schema:
            $ref: '#/definitions/response.API'
      summary: 種子
      tags:
      - 範例
  /api/suggest:
    post:
      description: 建議
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/errorcode.APIError'
      summary: 建議
      tags:
      - Talk
  /api/wf/game:
    get:
      responses:
        "200":
          description: 犯人在跳舞
          schema:
            type: string
      summary: 犯人在跳舞
      tags:
      - 遊戲
swagger: "2.0"
