apiVersion: v1
kind: ServiceAccount
metadata:
  name: drone-deploy
  namespace: default # 指定要部署的namespaces

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: drone-deploy
  namespace: default # 指定要部署的namespaces
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: drone-deploy
  namespace: default # 指定要部署的namespaces
subjects:
  - kind: ServiceAccount
    name: default
    namespace: devops
roleRef:
  kind: Role
  name: drone-deploy
  apiGroup: rbac.authorization.k8s.io
