name: Docker Image CI

on:
  push:
    branches: [action]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@2.9
        with:
          name: yam8511/gola
          username: ${{secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: ./Dockerfile
