name: Docker Image CI

on:
  push:
    branches: [action]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: docker/build-push-action@v1
        name: Build and Push the Docker image
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: yam8511/gola
          build_args: ENTER=server,BOT_TOKEN=${{ secrets.BOT_TOKEN }},${{ secrets.BOT_CHAT_ID }}
          tags: latest
